apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fbc-sample-repo-uvwm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fbc-sample-repo-uvwm
    app.kubernetes.io/part-of: test-app-704
  name: fbc-sample-repo-uvwm
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: fbc
      app.kubernetes.io/instance: fbc-sample-repo-uvwm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fbc
        app.kubernetes.io/instance: fbc-sample-repo-uvwm
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-704/fbc-sample-repo-uvwm@sha256:6d825196f822c05c05e402e418e4a9b0fc809de8875a4986ea14702e1ce0302a
        name: fbc
        ports:
        - containerPort: 50051
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 512Mi
status: {}
