apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-no-dockerfile-4jt2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-no-dockerfile-4jt2
    app.kubernetes.io/part-of: test-app-704
  name: nodejs-no-dockerfile-4jt2
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: nodejs-no-dockerfile-4jt2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: nodejs-no-dockerfile-4jt2
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-704/nodejs-no-dockerfile-4jt2@sha256:29bdfb30065484c2a07e0f0aec9bb25653ddc0da6d16a3cb53c0e1b5ca3e2e2e
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
