apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: retrodep-ht0r
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: retrodep-ht0r
    app.kubernetes.io/part-of: test-app-704
  name: retrodep-ht0r
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-retrodep
      app.kubernetes.io/instance: retrodep-ht0r
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-retrodep
        app.kubernetes.io/instance: retrodep-ht0r
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-704/retrodep-ht0r@sha256:7831c21c8899b6afa1f80cd760f43593fad0b1a9a9dde658849f724a91d10ffc
        name: my-retrodep
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
