apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: pip-e2e-test-rzyu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pip-e2e-test-rzyu
    app.kubernetes.io/part-of: test-app-704
  name: pip-e2e-test-rzyu
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: pip-e2e-test
      app.kubernetes.io/instance: pip-e2e-test-rzyu
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pip-e2e-test
        app.kubernetes.io/instance: pip-e2e-test-rzyu
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-704/pip-e2e-test-rzyu@sha256:0dd92fbe0e4955c74ab35144ec6dfe47bd350a5434efee0998d7f9979ba876ac
        name: pip-e2e-test
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
